# Generated by Django 5.1.1 on 2025-02-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobLanderAPI', '0013_remove_companyquestions_user_company_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='submitted_cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobLanderAPI.cv'),
        ),
    ]
