# Generated by Django 5.1.1 on 2025-02-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobLanderAPI', '0014_alter_application_submitted_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='cv',
        ),
    ]
