# Generated by Django 5.1.1 on 2025-02-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobLanderAPI', '0015_remove_cv_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cv',
            field=models.FileField(default=1, upload_to='cvs/'),
            preserve_default=False,
        ),
    ]
